// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDprMaJpjPg7srVl8cqwrw2WB4VvL6xRnE',
    appId: '1:1037257193910:web:54185d3af2350c248ca917',
    messagingSenderId: '1037257193910',
    projectId: 'todo-app-d1f92',
    authDomain: 'todo-app-d1f92.firebaseapp.com',
    storageBucket: 'todo-app-d1f92.firebasestorage.app',
    measurementId: 'G-GSYJBS79YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWmsLevn3bQzYN45DekRXdGaqcNE8Ochs',
    appId: '1:1037257193910:android:03b9c8614a226dae8ca917',
    messagingSenderId: '1037257193910',
    projectId: 'todo-app-d1f92',
    storageBucket: 'todo-app-d1f92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzuBdD__ClRDyOAnrw9eTMc_WE05oe0i8',
    appId: '1:1037257193910:ios:a21f9349875b9ed78ca917',
    messagingSenderId: '1037257193910',
    projectId: 'todo-app-d1f92',
    storageBucket: 'todo-app-d1f92.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzuBdD__ClRDyOAnrw9eTMc_WE05oe0i8',
    appId: '1:1037257193910:ios:a21f9349875b9ed78ca917',
    messagingSenderId: '1037257193910',
    projectId: 'todo-app-d1f92',
    storageBucket: 'todo-app-d1f92.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDprMaJpjPg7srVl8cqwrw2WB4VvL6xRnE',
    appId: '1:1037257193910:web:e3b36903b9a34b6e8ca917',
    messagingSenderId: '1037257193910',
    projectId: 'todo-app-d1f92',
    authDomain: 'todo-app-d1f92.firebaseapp.com',
    storageBucket: 'todo-app-d1f92.firebasestorage.app',
    measurementId: 'G-CTH3T38VXC',
  );
}
